### PR TITLE
Tweak test report

### PR DESCRIPTION
**Pull request by fornellas**
Tweak the test execution report to:

- Show successful, failed, skipped and not executed tests even when it is 0.
  - It is printed in dim white in this case.
  - When there's 1+ examples, it is printed with the same usual color code (green, red, yellow, cyan).
- Improve the message for slow imports, making it more visible and hinting what to do next.
- Add link to documentation: despite being comprehensive, few people refer to it, let's make this better.
- Add nice colored ASCII colored logo, because why not help branding ¯\_(ツ)_/¯

image

### CODE REVIEW

**Comment by fornellas** [comment]
@deathowl do you know about this failing build? https://app.circleci.com/pipelines/github/facebookincubator/TestSlide/2/workflows/135eecd8-7fb6-42bf-979b-77d65e7c4c8b/jobs/2

**Comment by deathowl** [comment]
> @deathowl do you know about these 2 build errors?

i think rebase should resolve them

**Review by deathowl — APPROVED** [review]

**Comment by fornellas** [comment]
I'll move this logo to the right in the next week or so, so it is not annoying to users.

**Comment by fornellas** [comment]
Moved logo to the right of the screen so it does not annoy:

- If stdout is a terminal:
  - if columns > 80 then it caps the logo to the 80th column (so it does not goes all the way to the right on big terminals).
  - else
    - if it can fit the logo then print it
    - else does not print it
- else
  - print the logo as if the terminal had 80 columns.

image

**Pull request merged**
